@hostname = {{baseUrl}}
@path = /auth
@host = {{hostname}}{{path}}

GET {{host}}/verify-token

###

POST {{host}}/login
Content-type: application/json

{
  "login": "pattuzzoj@gmail.com",
  "password": "Ju30042001"
}

###

POST {{host}}/register
Content-type: application/json

{
  "email": "pattuzzoj@gmail.com",
  "username": "reidenasf",
  "password": "Ju30042001"
}

###

POST {{host}}/activate-account
Content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNGQ4YTRiMC0zMTlmLTQ3ZTQtOTU4Ny02ZDczMmNmMWZjY2EiLCJlbWFpbCI6InBhdHR1enpvakBnbWFpbC5jb20iLCJpYXQiOjE3NDAyODI2ODAsImV4cCI6MTc0MDI4Mjk4MH0.t5RjPKCd-4NbQPsJEJJnYH0p5-363EkVIfdpUM4b9W8"
}

###

DELETE {{host}}/logout

###

@POST {{host}}/forgot-password
Content-type: application/json

{
  "email": "pattuzzoj@gmail.com"
}

###

POST {{host}}/reset-password
Content-type: application/json

{
  "password": "Ju30042001"
}