@hostname = {{baseUrl}}
@path = /auth
@host = {{hostname}}{{path}}

### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "password": "Password123!",
  "username": "testuser"
}

### Verify Email
POST http://localhost:5000/auth/verify-email
Content-Type: application/json

{
  "token": "<emailVerificationToken>"
}

### Resend Verification Email
POST http://localhost:5000/auth/resend-verification
Content-Type: application/json

{
  "token": "<emailVerificationToken>"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "login": "pattuzzoj@gmail.com",
  "password": "Ju30042001@"
}

### Refresh Token (requires cookie set from login)
POST http://localhost:5000/auth/refresh-token
Content-Type: application/json
Cookie: refresh-token=<refreshToken>

{}

### Verify Session (requires auth guard)
GET http://localhost:5000/auth/verify-session
Authorization: Bearer <accessToken>

### Logout (requires auth guard)
DELETE http://localhost:5000/auth/logout
Cookie: refresh-token=<refreshToken>

### Forgot Password
POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
  "account": "test@example.com"
}

### Reset Password
POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
  "token": "<resetToken>",
  "password": "NewPassword123!"
}

### Suspend Account (requires auth guard)
POST http://localhost:5000/auth/suspend-account
Authorization: Bearer <accessToken>
