@hostname = {{baseUrl}}
@path = /users
@host = {{hostname}}{{path}}

### Get Current User Profile
GET http://localhost:5000/users/me
Authorization: Bearer <accessToken>

### Check if Username Exists
GET http://localhost:5000/users/check-username?username=testuse

### Check if Email Exists
GET http://localhost:5000/users/check-email?email=test@example.com

### Request Change Email
POST http://localhost:5000/users/request-change-email
Authorization: Bearer <accessToken>
Content-Type: application/json

{
  "newEmail": "newemail@example.com"
}

### Confirm Change Email
POST http://localhost:5000/users/confirm-change-email
Authorization: Bearer <accessToken>
Content-Type: application/json

{
  "pin": "123456"
}

### Change Username
PATCH http://localhost:5000/users/me/username
Authorization: Bearer <accessToken>
Content-Type: application/json

{
  "username": "newusername"
}

### Change Password
PATCH http://localhost:5000/users/me/password
Authorization: Bearer <accessToken>
Content-Type: application/json

{
  "currentPassword": "OldPassword123!",
  "newPassword": "NewPassword123!"
}

### Delete User Data
DELETE http://localhost:5000/users/delete-data
Authorization: Bearer <accessToken>

### Delete User Account
DELETE http://localhost:5000/users
Authorization: Bearer <accessToken>
